services:
  app:
    image: analytics-api:v1
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=8080
    ports:
      - 8080:8080
    command: uvicorn main:app --host 0.0.0.0 --port 8080 --reload
    volumes:
      - ./src:/code:rw
    develop:
      watch:
        - action: rebuild
          path: Dockerfile
        - action: rebuild
          path: requirements.txt
        - action: rebuild
          path: requirements.txt
